apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: payment
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: payment
          image: vsamarin/payment:1.0.0
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8002
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: db.url
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: db.user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: db.password
            - name: CONTEXT_PATH
              value: /payment
            - name: DB_SCHEMA
              value: payment
            - name: CONDUCTOR_SERVER_URL
              value: https://developer.orkescloud.com/api
            - name: CONDUCTOR_AUTH_KEY
              value: spk39518fc1b-def0-11ef-aeb1-c259128d4f69
            - name: CONDUCTOR_AUTH_SECRET
              value: qezQQ336JPvw1azvCCfbOyXy6FuCnEKpIEaZotxLPdfcoqkr
