config:
  db:
    url: ${DB_URL}
    schema: ${DB_SCHEMA}
    user: ${DB_USER}
    password: ${DB_PASSWORD}

conductor:
  client:
    rootUri: https://developer.orkescloud.com/api #http://localhost:8080/api
    keyId: spk39518fc1b-def0-11ef-aeb1-c259128d4f69
    secret: qezQQ336JPvw1azvCCfbOyXy6FuCnEKpIEaZotxLPdfcoqkr
  server:
    url: https://developer.orkescloud.com/api
    keyId: spk39518fc1b-def0-11ef-aeb1-c259128d4f69
    secret: qezQQ336JPvw1azvCCfbOyXy6FuCnEKpIEaZotxLPdfcoqkr
